services:
  nwaku1:
    image: wakuorg/nwaku:v0.24.0
    container_name: nwaku1
    ports:
      - '21161:21161'
      - '21162:21162'
      - '21163:21163'
      - '21164:21164'
      - '21165:21165'
    volumes:
      - ./scripts/run-node-1.sh:/opt/run_node.sh:Z
    entrypoint: sh
    command:
      - /opt/run_node.sh
    networks:
      waku:
        ipv4_address: 172.18.111.226

  nwaku2:
    image: wakuorg/nwaku:v0.24.0
    container_name: nwaku2
    ports:
      - '21171:21161'
      - '21172:21162'
      - '21173:21163'
      - '21174:21164'
      - '21175:21165'
    volumes:
      - ./scripts/run-node-2.sh:/opt/run_node.sh:Z
    entrypoint: sh
    command:
      - /opt/run_node.sh
    networks:
      waku:
        ipv4_address: 172.18.111.227
    depends_on: [nwaku1]

networks:
  waku:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
