name: Waku Nodes Tests
on:
  pull_request:
    branches: [main, master]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Starting Waku Nodes
        run: docker compose -f docker-compose.yml up -d --build

      - name: Starting Tests
        run: docker compose -f docker-compose-tests.yml up --build

      - name: Teardown
        run: |
          docker compose -f docker-compose-tests.yml down
          docker compose -f docker-compose.yml down
